import { GltfData } from "../GltfData";

import { ValidationIssue } from "../../ValidationIssue";
import { GltfExtensionIssues } from "../GltfExtensionIssues";

/**
 * A class for processing the list of issues that are generated by
 * the glTF validator, to filter out the issues that are obsolete
 * due to the validation from the ExtMeshFeaturesValidator.
 *
 * @internal
 */
export class ExtMeshFeaturesIssues {
  /**
   * Process the given list of validation issues, and possibly filer
   * out the issues that are obsolete due to the validation that
   * is performed by 'validateGltf'.
   *
   * @param path - The path for validation issues
   * @param keepObsoleteIssues - Whether issues should be retained even
   * when they are obsolete.
   * @param gltfData - The GltfData objects
   * @param causes - The validation issues
   */
  static async processCauses(
    path: string,
    keepObsoleteIssues: boolean,
    gltfData: GltfData,
    causes: ValidationIssue[]
  ): Promise<ValidationIssue[]> {
    if (keepObsoleteIssues) {
      return causes;
    }
    const usedAccessorIndices =
      ExtMeshFeaturesIssues.computeUsedAccessorIndices(gltfData.gltf);
    const usedTextureIndices = ExtMeshFeaturesIssues.computeUsedTextureIndices(
      gltfData.gltf
    );

    // Remove the issue about the extension not being supported
    const isAboutUnsupportedExtension =
      GltfExtensionIssues.isAboutUnsupportedExtension("EXT_mesh_features");

    // Remove issues about unused objects for buffer views and
    // textures that are actually used by the extension
    const isAboutUnusedAccessor = GltfExtensionIssues.isAboutUnusedObject(
      "accessors",
      usedAccessorIndices
    );
    const isAboutUnusedTexture = GltfExtensionIssues.isAboutUnusedObject(
      "textures",
      usedTextureIndices
    );

    const processedCauses: ValidationIssue[] =
      await GltfExtensionIssues.processCausesWith(
        causes,
        isAboutUnsupportedExtension,
        isAboutUnusedAccessor,
        isAboutUnusedTexture
      );
    return processedCauses;
  }

  /**
   * Pragmatically drill into the given glTF object to find all accessor
   * indices that are used via feature ID attributes or as texture
   * coordinate accessors for feature ID textures.
   *
   * This will fall back to empty objects and arrays everywhere, and return
   * only the indices that are definitely known to be used.
   *
   * @param gltf - The glTF JSON object
   * @returns The accessor indices that are used by the
   * EXT_mesh_features extension
   */
  private static computeUsedAccessorIndices(gltf: any): Set<number> {
    const accessorIndices = new Set<number>();
    const meshes = gltf.meshes ?? [];
    for (const mesh of meshes) {
      const primitives = mesh.primitives ?? [];
      for (const primitive of primitives) {
        const extensions = primitive.extensions ?? {};
        const extension = extensions["EXT_mesh_features"] ?? {};
        const featureIds = extension.featureIds ?? [];
        for (const featureId of featureIds) {
          const attributeAccessorIndex = featureId.attribute;
          if (typeof attributeAccessorIndex === "number") {
            accessorIndices.add(attributeAccessorIndex);
          }
          const texture = featureId.texture ?? {};
          const texcoordAccessorIndex = texture.texCoord;
          if (typeof texcoordAccessorIndex === "number") {
            accessorIndices.add(texcoordAccessorIndex);
          }
        }
      }
    }
    return accessorIndices;
  }

  /**
   * Pragmatically drill into the given glTF object to find all texture
   * indices that are used via feature ID textures
   *
   * This will fall back to empty objects and arrays everywhere, and return
   * only the indices that are definitely known to be used.
   *
   * @param gltf - The glTF JSON object
   * @returns The texture indices that are used by the
   * EXT_mesh_features extension
   */
  private static computeUsedTextureIndices(gltf: any): Set<number> {
    const textureIndices = new Set<number>();
    const meshes = gltf.meshes ?? [];
    for (const mesh of meshes) {
      const primitives = mesh.primitives ?? [];
      for (const primitive of primitives) {
        const extensions = primitive.extensions ?? {};
        const extension = extensions["EXT_mesh_features"] ?? {};
        const featureIds = extension.featureIds ?? [];
        for (const featureId of featureIds) {
          const texture = featureId.texture ?? {};
          const textureIndex = texture.index;
          if (typeof textureIndex === "number") {
            textureIndices.add(textureIndex);
          }
        }
      }
    }
    return textureIndices;
  }
}
