import { ValidationIssue } from "../../ValidationIssue";
import { GltfData } from "../GltfData";
import { GltfExtensionIssues } from "../GltfExtensionIssues";

/**
 * Functions for implementing filters on lists of validation issues,
 * related to the KHR_texture_basisu extension
 *
 * @internal
 */
export class KhrTextureBasisuIssues {
  /**
   * Process the given list of issues in view of KHR_texture_basisu.
   *
   * This will omit the issues that are considered obsolete due to
   * the lack of support for KHR_texture_basisu validation.
   *
   * @param path - The path for validation issues
   * @param keepObsoleteIssues - Whether issues should be retained even
   * when they are obsolete.
   * @param gltfData - The GltfData
   * @param causes - The causes
   * @returns The filtered causes
   */
  static async processCauses(
    path: string,
    keepObsoleteIssues: boolean,
    gltfData: GltfData,
    causes: ValidationIssue[]
  ): Promise<ValidationIssue[]> {
    if (keepObsoleteIssues) {
      return causes;
    }
    const gltf = gltfData.gltf;

    // Remove the issue about the extension not being supported
    const isAboutUnsupportedExtension =
      GltfExtensionIssues.isAboutUnsupportedExtension("KHR_texture_basisu");

    // Remove the issue about the unused image object when the image is used
    const usedImageIndices =
      KhrTextureBasisuIssues.computeUsedImageIndices(gltf);
    const isAboutUnusedImage = GltfExtensionIssues.isAboutUnusedObject(
      "images",
      usedImageIndices
    );

    // Remove the issues about unsupported mime type and image format
    const isAboutKtx = KhrTextureBasisuIssues.isAboutKtx(usedImageIndices);

    const processedCauses: ValidationIssue[] =
      await GltfExtensionIssues.processCausesWith(
        causes,
        isAboutUnsupportedExtension,
        isAboutUnusedImage,
        isAboutKtx
      );
    return processedCauses;
  }

  /**
   * Returns whether the given issue is an issue that should be removed
   * because it is caused by the lack of support of the KHR_texture_basisu
   * extension in the glTF validator.
   *
   * @param usedImageIndices - The indices of images that
   * are used by the KHR_texture_basisu extension
   * @param issue - The validation issue
   * @returns Whether the issue should be removed
   */
  private static isAboutKtx(
    usedImageIndices: Set<number>
  ): (issue: ValidationIssue) => Promise<boolean> {
    const predicate = async (issue: ValidationIssue) => {
      // Remove all INFO- and WARNING issues about
      // - invalid KTX MIME type
      // - unrecognized image format
      // for issues that refer to a path starting with "/images/N"
      // where N is one of the images that are referred to by
      // the KHR_texture_basisu extension in any texture.
      const message = issue.message;
      const path = issue.path;
      if (
        message.startsWith("Invalid value 'image/ktx2'.") ||
        message.startsWith("Image format not recognized.")
      ) {
        const imageIndex = GltfExtensionIssues.extractIndex("images", path);
        if (imageIndex === undefined) {
          // This is making some assumptions about the path that
          // is generated by the glTF validator. Just print a
          // warning for the case that this ever breaks.
          //console.warn("Could not extract image index from path: " + path);
          return false;
        }
        return usedImageIndices.has(imageIndex);
      }
      return false;
    };
    return predicate;
  }

  /**
   * Compute the indices of all images that appear as any
   * <code>gltf.textures[i].extensions["KHR_texture_basisu"].source</code>.
   *
   * @param gltf - The glTF JSON object
   * @returns The image indices
   */
  private static computeUsedImageIndices(gltf: any): Set<number> {
    const imageIndices = new Set<number>();
    const textures = gltf.textures ?? [];
    for (const texture of textures) {
      const extensions = texture.extensions ?? {};
      const extension = extensions["KHR_texture_basisu"] ?? {};
      const source = extension.source;
      if (typeof source === "number") {
        imageIndices.add(source);
      }
    }
    return imageIndices;
  }
}
