import fs from "fs";
import path from "path";

import { ResourceResolvers } from "3d-tiles-tools";

import { ValidationContext } from "../../src/validation/ValidationContext";
import { ValidationResult } from "../../src/validation/ValidationResult";

import { GltfDataReader } from "../../src/validation/gltf/GltfDataReader";
import { GltfExtensionValidators } from "../../src/validation/gltf/GltfExtensionValidators";

import { IoValidationIssues } from "../../src/issues/IoValidationIssue";

/**
 * An INTERNAL utility function that is only intended to be used in the
 * specs: It ONLY performs the glTF validation that is implemented as
 * part of the 3D Tiles Validator.
 *
 * It will NOT perform a full validation with the glTF-Validator. It assumes
 * that the part of the glTF file that is checked with the glTF-Validator
 * is already valid.
 *
 * This is intended for the use in the specs, where the validation result
 * is checked to contain the validation issues that are generated by the
 * 3D Tiles Validator implementation, without the distraction from the
 * glTF-Validator issues.
 *
 *
 * @param gltfFileName - The glTF file name
 * @returns The validation result
 */
export async function validateGltf(
  gltfFileName: string
): Promise<ValidationResult> {
  fs.readFileSync(gltfFileName);

  const directory = path.dirname(gltfFileName);
  const fileName = path.basename(gltfFileName);
  const resourceResolver =
    ResourceResolvers.createFileResourceResolver(directory);
  const context = new ValidationContext(directory, resourceResolver);
  const gltfFileData = await resourceResolver.resolveData(fileName);
  if (!gltfFileData) {
    const message = `Could not read glTF for specs`;
    const issue = IoValidationIssues.IO_ERROR(gltfFileName, message);
    context.addIssue(issue);
  } else {
    // If this fails, and issue will be added to the context:
    const gltfData = await GltfDataReader.readGltfData(
      gltfFileName,
      gltfFileData,
      context
    );
    if (gltfData) {
      await GltfExtensionValidators.validateGltfExtensions(
        gltfFileName,
        gltfData,
        context
      );
    }
  }
  const validationResult = context.getResult();
  return validationResult;
}
